version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    deploy:
      resources:
        limit:
          cpus: "0.50"
          memory: 512M

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
