name: Secure Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-secure-api:latest .

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/flask-secure-api:latest
          severity: HIGH,CRITICAL

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-secure-api:latest
